name: Format

on:
  issue_comment:
    types: [created]

jobs:
  format:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/format')
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Format Code
      working-directory: ./ui
      run: |
        npm install
        npx prettier --write .

    # Commit changes from prettier
    - uses: stefanzweifel/git-auto-commit-action@v5
